name: AutoUpdate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 2,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Build Game
        run: |
          npm install
          node markData_i18n.js ${{ secrets.PASS_KEY }} true
      - name: Commit
        run: |
          git config --global user.email lie58600@gmail.com
          git config --global user.name lie
          git add .
          git commit -m "自动更新" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.LIE_GITHUB_TOKEN }}
